version: "3"

services:
  db:
    image: "postgres:13-alpine"
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: postgres
      TZ: UTC
      PGTZ: UTC
    volumes:
      - ~/docker-data/cryptohub/postgresql:/var/lib/postgresql/data
